name: instagram
description: A new Flutter application.
version: 1.2.3+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  cloud_firestore: ^3.2.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.0
  firebase_auth: ^3.4.0
  google_sign_in: ^5.0.0
  uuid: ^3.0.1
  image: ^3.0.1
  font_awesome_flutter: ^10.1.0
  async: ^2.4.0
  http: ^0.13.0
  shared_preferences: ^2.0.4
  cached_network_image: ^3.2.1
  firebase_messaging: ^11.4.3
  location: ^4.1.1
  geocoder: ^0.2.1
  flare_flutter: ^3.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_database: ^9.1.0
  firebase_analytics: ^9.3.0
  firebase_app_check: ^0.0.6+18
  cloud_functions: ^3.3.3
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_in_app_messaging: ^0.6.0+20
  firebase_app_installations: ^0.1.1+3
  firebase_remote_config: ^2.0.13

#dev_dependencies:
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
  - family: Billabong
    fonts:
    - asset: assets/fonts/Billabong.ttf
  assets:
  - assets/images/google_signin_button.png
  - assets/flare/Like.flr
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schuyler
  #     fonts:
  #       - asset: fonts/Schuyler-Regular.ttf
  #       - asset: fonts/Schuyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
